on:
  push:
  schedule:
    - cron: '0 0 * * *'

name: render_site

jobs:
  render_site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rmarkdown", "dplyr", "lubridate"))
        shell: Rscript {0}

      - name: Render site
        run: rmarkdown::render_site(encoding = 'UTF-8')
        shell: Rscript {0}

      - name: Push
        run: |
          git commit -a 'Build site' || echo "No changes to commit"
          git push origin master || echo "No changes to commit"

