on:
  push:
  schedule:
    - cron: '0 0 * * *'

name: render_site

jobs:
  render_site:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: r-${{ hashFiles('events.Rmd') }}
          restore-keys: r-

      - name: Install system dependencies
        run: sudo apt install libcurl4-openssl-dev

      - name: Install dependencies
        run: |
          install.packages(c("rmarkdown", "dplyr", "tidyr", "purrr", stringr", "lubridate", "googlesheets4", "glue"))
        shell: Rscript {0}

      - name: Render site
        run: rmarkdown::render_site(encoding = 'UTF-8')
        shell: Rscript {0}

      - name: Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -a -m 'Build site' || echo "No changes to commit"
          git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }} || echo "No changes to commit"
