on:
  push:
  schedule:
    - cron: '0 0 * * *'

name: render_site

jobs:
  render_site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: r-${{ hashFiles('events.Rmd') }}

      - name: Install system dependencies
        run: sudo apt install libcurl4-openssl-dev

      - name: Install dependencies
        run: |
          install.packages(c("rmarkdown", "dplyr", "tidyr", "stringr", "lubridate", "googlesheets4", "glue"))
        shell: Rscript {0}

      - name: Render site
        run: rmarkdown::render_site(encoding = 'UTF-8')
        shell: Rscript {0}

      - name: Push
        run: |
          git commit -a -m 'Build site' || echo "No changes to commit"
          git push origin master || echo "No changes to commit"

