on:
  push:
  schedule:
    - cron: '0 0 * * *'

name: render_site

jobs:
  render_site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: r-${{ hashFiles('events.Rmd') }}

      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "install.packages('remotes')" -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"

      - name: Install dependencies
        run: |
          install.packages(c("rmarkdown", "dplyr", "tidyr", "lubridate", "googlesheets4", "glue"))
        shell: Rscript {0}

      - name: Render site
        run: rmarkdown::render_site(encoding = 'UTF-8')
        shell: Rscript {0}

      - name: Push
        run: |
          git commit -a 'Build site' || echo "No changes to commit"
          git push origin master || echo "No changes to commit"

